export const TX_HISTORY_ENV = {
  BATCH_PARALLELISM: Number(process.env.NEXT_PUBLIC_TX_HISTORY_BATCH_PARALLELISM ?? 10),
  TRANSFORM_PARALLELISM: Number(process.env.NEXT_PUBLIC_TX_HISTORY_TRANSFORM_PARALLELISM ?? 3),
  PAUSE_SIZE_DAYS: Number(process.env.NEXT_PUBLIC_TX_HISTORY_PAUSE_SIZE_DAYS ?? 30),
  PAGE_SIZE: Number(process.env.NEXT_PUBLIC_TX_HISTORY_PAGE_SIZE ?? 1_000),
  BATCH_BLOCKS_DEFAULT: Number(process.env.NEXT_PUBLIC_TX_HISTORY_BATCH_BLOCKS_DEFAULT ?? 5_000_000),
  BATCH_BLOCKS_APECHAIN: Number(process.env.NEXT_PUBLIC_TX_HISTORY_BATCH_BLOCKS_APECHAIN ?? 5_000_000),
  BATCH_BLOCKS_MUSTER: Number(process.env.NEXT_PUBLIC_TX_HISTORY_BATCH_BLOCKS_MUSTER ?? 10_000),
  BATCH_BLOCKS_TREX: Number(process.env.NEXT_PUBLIC_TX_HISTORY_BATCH_BLOCKS_TREX ?? 10_000),
  SWR_DEDUPING_INTERVAL_MS: Number(
    process.env.NEXT_PUBLIC_TX_HISTORY_SWR_DEDUPING_INTERVAL_MS ?? 1_000_000,
  ),
  ALCHEMY_DELAY_MS: Number(process.env.NEXT_PUBLIC_TX_HISTORY_ALCHEMY_DELAY_MS ?? 2_000),
  TIMESTAMP_ENRICH_CONCURRENCY: Number(
    process.env.NEXT_PUBLIC_TX_HISTORY_TIMESTAMP_ENRICH_CONCURRENCY ?? 0,
  ),
} as const;
