name: Restore build artifacts
description: Restore build artifacts

inputs:
  name:
    description: Name of the build artifact to download
    required: false
    default: build-artifacts

runs:
  using: composite
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: packages/app
