name: Batch Poster Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours

jobs:
  run-monitoring:
    name: Batch Poster Monitor (${{ matrix.chain == 'orbit' && 'Orbit' || matrix.chain == 'core' && 'Core' || matrix.chain == 'enterprise' && 'Enterprise' || matrix.chain }})
    strategy:
      matrix:
        chain: [core, orbit, enterprise]
    uses: ./.github/workflows/monitoring.yml
    with:
      chain: ${{ matrix.chain }}
      monitor: batch-poster
    secrets: inherit
